### ISSUE TITLE
Support for Python 3.8 and 3.9

### ISSUE THREAD

**Issue by r4victor** [Ovsyanka83/cached_classproperty#5]
`cached_classproperty` claims to support Python >= 3.8 but works only on Python >= 3.10 because of the typing union operator used ("|"). The operator should be replaced with `Union`/`Optional` to support versions before 3.10.

Related to https://github.com/zmievsa/pydantic-duality/issues/8.

**Comment by zmievsa** [comment]
Thanks! Will take care of it.

**Comment by zmievsa** [comment]
Released as a part of 1.0.1. Big thanks!
